<funkload version="1.16.1" time="2015-10-24T14:05:52.288659">
<config key="sleep_time_min" value="0.0" />
<config key="node" value="devcat" />
<config key="startup_delay" value="0.01" />
<config key="cycles" value="[1]" />
<config key="cycle_time" value="1.0" />
<config key="description" value="Access the main URL 20 times" />
<config key="configuration_file" value="/data/git/nebula2/loadtest/CDMI.conf" />
<config key="class_title" value="CDMI FunkLoad tests" />
<config key="server_url" value="http://localhost:8080/cdmi/new_container7/new_object8.txt" />
<config key="module" value="test_cdmi" />
<config key="id" value="test_cdmi" />
<config key="class_description" value="Test the CDMI server" />
<config key="sleep_time" value="0.01" />
<config key="sleep_time_max" value="0.5" />
<config key="duration" value="10" />
<config key="method" value="test_cdmi" />
<config key="log_xml" value="/data/git/nebula2/loadtest/cdmi-bench.xml" />
<config key="class" value="CDMI" />
<config key="localhost" value="The benching and benched machine" />
<config key="python_version" value="2.7.6" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713552.29" duration="0.666524171829">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:52 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713552.29" result="Failure" steps="1" duration="0.667958021164" connection_duration="0.666524171829" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713552.97" duration="0.507905960083">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:53 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713552.97" result="Failure" steps="1" duration="0.508805036545" connection_duration="0.507905960083" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713553.49" duration="0.498075008392">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:53 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713553.49" result="Failure" steps="1" duration="0.498903989792" connection_duration="0.498075008392" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713554.0" duration="0.493616819382">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:54 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713554.0" result="Failure" steps="1" duration="0.494455099106" connection_duration="0.493616819382" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713554.51" duration="0.502368927002">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:54 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713554.51" result="Failure" steps="1" duration="0.503134012222" connection_duration="0.502368927002" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713555.02" duration="0.496709108353">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:55 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713555.02" result="Failure" steps="1" duration="0.497123003006" connection_duration="0.496709108353" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713555.53" duration="0.500962018967">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:55 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713555.53" result="Failure" steps="1" duration="0.501549005508" connection_duration="0.500962018967" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713556.04" duration="0.484831094742">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:56 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713556.04" result="Failure" steps="1" duration="0.485430955887" connection_duration="0.484831094742" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713556.54" duration="0.49064207077">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:56 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713556.54" result="Failure" steps="1" duration="0.491191148758" connection_duration="0.49064207077" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713557.04" duration="0.498857975006">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:57 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713557.04" result="Failure" steps="1" duration="0.499615907669" connection_duration="0.498857975006" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713557.55" duration="0.56196808815">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:58 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713557.55" result="Failure" steps="1" duration="0.562510967255" connection_duration="0.56196808815" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713558.12" duration="0.49328494072">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:58 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713558.12" result="Failure" steps="1" duration="0.493981122971" connection_duration="0.49328494072" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713558.62" duration="0.53587603569">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:59 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713558.62" result="Failure" steps="1" duration="0.53630399704" connection_duration="0.53587603569" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713559.17" duration="0.478311061859">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:05:59 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713559.17" result="Failure" steps="1" duration="0.479158163071" connection_duration="0.478311061859" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713559.66" duration="0.493292093277">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:06:00 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713559.66" result="Failure" steps="1" duration="0.493710041046" connection_duration="0.493292093277" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713560.17" duration="0.526748180389">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:06:00 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713560.17" result="Failure" steps="1" duration="0.52757692337" connection_duration="0.526748180389" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713560.7" duration="0.506509065628">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:06:01 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713560.7" result="Failure" steps="1" duration="0.507389068604" connection_duration="0.506509065628" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713561.22" duration="0.52298784256">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:06:01 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713561.22" result="Failure" steps="1" duration="0.523718118668" connection_duration="0.52298784256" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
<response cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi" step="001" number="001" type="get" result="Failure" url="/cdmi/new_container7/new_object8.txt" code="500" description="Get URL" time="1445713561.76" duration="0.495685815811">
  <headers>
    <header name="date" value="Sat, 24 Oct 2015 19:06:02 GMT" />
    <header name="content-length" value="0" />
    <header name="server" value="Cowboy" />
  </headers>
  <body><![CDATA[
None
]]>
  </body>
</response>
<testResult cycle="000" cvus="001" thread="000" suite="CDMI" name="test_cdmi"  time="1445713561.76" result="Failure" steps="1" duration="0.496182918549" connection_duration="0.495685815811" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/data/git/nebula2/loadtest/test_cdmi.py&quot;, line 26, in test_cdmi&#10;    self.get(server_url, description='Get URL')&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 216, in _connect&#10;    raise self.failureException, str(value.response)&#10; AssertionError: /cdmi/new_container7/new_object8.txt&#10;HTTP Response 500: Internal Server Error&#10;" />
</funkload>
